### ISSUE TITLE
KM Admin should be able to invite others users and make users admin in the KM.

### ISSUE THREAD

**Issue by DowLucas** [DowLucas/PubGo#5]
Be able to invite people via email to the KM and set people to admin within the KM.

**Comment by OllanBollan** [comment]
First iteration of this will be to create a way for the club master to add people to the KM in the web app and to see a list of users authorized for the KM. 

2nd Iteration is for the club master to be able to set a new club master and for the new club master to remove old users/old club master. 

3rd iteration is sending email invites. This is indefinitely put on hold, as it requires setting up a dedicated email service to implement.

**Comment by OllanBollan** [comment]
Resolved in pull request [#33](https://github.com/DowLucas/PubGo/pull/33)
